---
name: 8xFF HA relayer agent
description: Decentralized HomeAssistant Proxy
version: 0.1.7
slug: 8xff_ha_relayer
init: false
host_network: true
url: https://github.com/8xFF/atm0s-decentralized-home-assistant-proxy
codenotary: hello@8xff.io
image: "ghcr.io/8xff/atm0s-decentralized-home-assistant-proxy-{arch}"
map:
  - ssl:rw
arch:
  - aarch64
  - amd64
  - armv7
  - i386
options:
  connector_addr: 127.0.0.1:33333
  connector_protocol: tcp
  http_dest: 127.0.0.1:8080
  https_dest: 127.0.0.1:8443
  local_key: 8xff.pem
schema:
  connector_addr: str
  connector_protocol: str
  http_dest: str
  https_dest: str
  local_key: str
