[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["default", "attributes", "unstable"] }
async-trait = "0.1.74"
futures = "0.3.4"
httparse = "1.8.0"
log = "0.4.20"
tls-parser = "0.11.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "std"] }
yamux = "0.13.1"
